# Default initial positions for my_robot's ros2_control fake system

initial_positions:
  arm_joint_1_1: 0
  arm_joint_3_1: 0
  arm_joint_5_1: 0
  arm_joint_7_1: 0
  arm_veer_joint_1: 0
  arm_veer_joint_2: 0
  arm_veer_joint_3: 0
  arm_veer_joint_4: 0
  wheel_joint_1: 0
  wheel_joint_2: 0
  wheel_joint_3: 0
  wheel_joint_4: 0