# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
# moveit_controller_manager: moveit_fake_controller_manager/MoveItFakeControllerManager

moveit_simple_controller_manager:
  controller_names:
    - veer_controller
    - wheel_controller
    - arm_1_controller

  veer_controller:
    type: FollowJointTrajectory
    joints:
      - arm_veer_joint_4
      - arm_veer_joint_3
      - arm_veer_joint_2
      - arm_veer_joint_1
    action_ns: follow_joint_trajectory
    default: true
  wheel_controller:
    type: FollowJointTrajectory
    joints:
      - wheel_joint_4
      - wheel_joint_3
      - wheel_joint_2
      - wheel_joint_1
  arm_1_controller:
    type: FollowJointTrajectory
    joints:
      - arm_joint_1_1
      - arm_joint_3_1
      - arm_joint_5_1
      - arm_joint_7_1